#!/bin/bash

#Check if exactly one argument is provided

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <FileName>"
	exit1
fi

# File name
FILE=$1

#Check if the file exists
if [ ! -e "$FILE" ]; then
	echo "FIle not exist: $FILE"
	exit 1
fi

# Check if the file is a directory
if [ -d "$FILE" ]; then
	echo "$FILE is a directory."
elif [ -f "$FILE" ]; then
	echo "$FILE is a regular file."
else
	ehco "$FILE is neither a regilar file nor a directory."
fi

# Get file permissions
PERMISSIONS=$(ls -ld "$FILE" | awk '{print $1}')
echo "Permissions: $PERMISSIONS"

# Get file size
SIZE=$(stat -c%s "$FILE")
echo "Size: $SIZE bytes"
