#!/bin/bash

# Prompt the user for a number
echo "Please enter a number:"
read number

# Check if the number is positive, neagtive or zero
if (( number > 0 )); then
	echo "The number is positive."
elif (( number < 0 )); then
	echo "The number is negative."
else
	echo "The number is zero."
fi
